// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MovieTime
{
	public partial class MovieDetailCell : UITableViewCell
	{
		public MovieDetailCell (IntPtr handle) : base (handle)
		{
		}

		public UIImageView MoviePoster => moviePoster;

		public UILabel MovieTitle => movieName;

		public UILabel OverviewText => overviewText;

		public UILabel BudgetText => budgetText;

		public UILabel BudgetBox => budgetBox;

		public UILabel RevenueText => revenueText;

		public UILabel RevenueBox => revenueBox;

		public UILabel GenreText => genreText;

		public UILabel TaglineText => taglineText;

		public UILabel RelatedMovies => relatedMovies;

		public UILabel FirstRelatedMovie => firstRelatedMovie;

		public UILabel SecondRelatedMovie => secondRelatedMovie;

		public UILabel ThirdRelatedMovie => thirdRelatedMovie;

		public UIImageView FirstRelatedImage => firstRelatedImage;

		public UIImageView SecondRelatedImage => secondRelatedImage;

		public UIImageView ThirdRelatedImage => thirdRelatedImage;

		public UIStackView BudgetStack => budgetStack;

		public UIStackView RevenueStack => revenueStack;



	}
}
