// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using MovieTime.Data.Model;
using MovieTime.Data.Services;
using Refit;
using SDWebImage;
using UIKit;

namespace MovieTime
{
	public partial class MovieDetailController : UITableViewController
	{
		
        Movie movie;
        const string key = "e9e4e4b144f5468cd2b2aa222f12f699";
        string imageToShow;
        IRefitMovieTimeService manager = RestService.For<IRefitMovieTimeService>("https://api.themoviedb.org");

        public MovieDetailController (IntPtr handle) : base (handle)
		    {
		    }
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            movie = manager.GetMovieById(key, "581389").Result;
        }

        

        public override nint RowsInSection(UITableView tableView, nint section)
        {
            return 1;
        }
    }
}
